### ISSUE TITLE
Cannot install pulseeffects-4.4.7 (Gentoo): ../pulseeffects-4.4.7/src/spectrum_ui.cpp:26:26: error: cannot call member function ‘void SpectrumUi::init_custom_color()’ without object init_custom_color();

### ISSUE THREAD

**Issue by mgwolff** [wwmm/pulseeffects#444]
Hello,

When installing pulseeffects-4.4.7 on Gentoo, the installation fails with various errors, such as:

```
/pulseeffects-4.4.7/src/spectrum_ui.cpp:26:26: error: cannot call member function ‘void SpectrumUi::init_custom_color()’ without object 
         init_custom_color();
```

I reported a Gentoo bug and it was suggested that I create an upstream bug.
Please find the full build log attached.
[build.log](https://github.com/wwmm/pulseeffects/files/2896364/build.log)

I tried downloading the sources and manually building pulseeffects-4.4.7, but I got similar errors.

**Comment by wwmm** [comment]
Strange. It builds fine on Arch Linux. In your log I saw `FAILED: src/src@@pulseeffects@exe/spectrum_ui.cpp.o `. This explains all the other failures. But it is not clear why this file cannot be compiled on gentoo. Maybe it is a compiler problem. Here on Arch Linux I have `gcc 8.2.1+20181127-1`. But on your log I see `gcc 6.4.0`

**Comment by wwmm** [comment]
It also builds on Arch Linux with `clang 7.0.1`. I configured meson with `CC=clang CXX=clang++ meson build_dir`

**Comment by mgwolff** [comment]
After switching from gcc-6.4.0 to gcc-7.3.0, pulseeffects-4.4.7 compiled successfully.

**Comment by mgwolff** [comment]
Thank you!
